void InitRenderStack();
void SetStackSize(int STSize);
short xGetHeight(int x,int y);
void SetLight(int Ldx,int Ldy,int Ldz);
void AddHeight(int x,int y,int dh);
void CreateBlob(int x,int y,int h,int r);
void InitRenderMap();
void RotateTeta();
void RotateTetaI();
void RotatePhi();
void RotatePhiI();