//extern byte WaterDeep [(MAPSX*MAPSY)>>2];
extern byte* WaterDeep;
void HandleWater();
void InitWater();
void SetWaterSpot(int x,int y,int r);
void EraseWaterSpot(int x,int y,int r);
void DeepWaterSpot(int x,int y,int r);
void MakeBrod(int x,int y,int r);
extern int WaterEditMode;
extern int CostThickness;
void SetupSpot();
void SpotByUnit(int x,int y,int r,byte dir);
void SetBrightSpot(int x,int y,int Brightness,bool dir);
void CreateWaterLocking(int x,int y,int x1,int y1);